# Site settings
title: ExCommerce
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/page" # the subpath of your site, e.g. /blog/
url: "https://canarytechnology.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
